import streamlit as st
import groq
import base64
import sqlite3
from PIL import Image
import io
from datetime import datetime
import json
import re
import requests

# Database setup
def init_db():
    conn = sqlite3.connect("diagnoses.db")
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS diagnoses (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            crop_name TEXT,
            disease TEXT,
            severity TEXT,
            yield_loss TEXT,
            treatment TEXT,
            medicine TEXT,
            language TEXT,
            date TEXT
        )
    """)
    conn.commit()
    conn.close()

def save_diagnosis(crop_name, disease, severity, yield_loss, treatment, medicine, language):
    conn = sqlite3.connect("diagnoses.db")
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO diagnoses (crop_name, disease, severity, yield_loss, treatment, medicine, language, date)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    """, (crop_name, disease, severity, yield_loss, treatment, medicine, language, datetime.now().strftime("%Y-%m-%d %H:%M")))
    conn.commit()
    conn.close()

def get_all_diagnoses():
    conn = sqlite3.connect("diagnoses.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM diagnoses ORDER BY date DESC")
    rows = cursor.fetchall()
    conn.close()
    return rows

def encode_image(image_file):
    img = Image.open(image_file)
    if img.mode != "RGB":
        img = img.convert("RGB")
    buffer = io.BytesIO()
    img.save(buffer, format="JPEG")
    return base64.standard_b64encode(buffer.getvalue()).decode("utf-8")

def generate_report(data):
    return f"""
╔══════════════════════════════════════╗
         🌱 CROPDOCTOR REPORT
╚══════════════════════════════════════╝

Date        : {data['date']}
Crop        : {data['crop']}
Language    : {data['language']}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DISEASE     : {data['disease']}
SEVERITY    : {data['severity']}
YIELD LOSS  : {data['yield_loss']}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CAUSE:
{data['cause']}

TREATMENT:
{data['treatment']}

MEDICINE TO BUY:
{data['medicine']}

PREVENTION:
{data['prevention']}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by CropDoctor AI
"""

def get_weather_risk(location):
    try:
        url = f"https://wttr.in/{location}?format=j1"
        response = requests.get(url, timeout=5)
        data = response.json()
        temp = float(data['current_condition'][0]['temp_C'])
        humidity = float(data['current_condition'][0]['humidity'])
        desc = data['current_condition'][0]['weatherDesc'][0]['value']
        risks = []
        if humidity > 80:
            risks.append("🍄 High humidity — high risk of **fungal diseases** (blast, blight)")
        if humidity > 70 and temp > 25:
            risks.append("🦠 Warm & humid — watch for **bacterial infections**")
        if temp > 35:
            risks.append("☀️ Very hot — risk of **heat stress and wilting**")
        if temp < 15:
            risks.append("❄️ Cool weather — risk of **powdery mildew**")
        if not risks:
            risks.append("✅ Weather conditions look safe for crops today")
        return {"temp": temp, "humidity": humidity, "desc": desc, "risks": risks}
    except:
        return None

def get_crop_calendar(crop):
    calendars = {
        "rice": [
            ("Jan-Feb", "Land preparation & nursery", "🌱"),
            ("Mar-Apr", "Transplanting", "🌾"),
            ("May-Jun", "Fertilizer application", "💊"),
            ("Jul-Aug", "Pest monitoring", "🔍"),
            ("Sep-Oct", "Harvesting", "🌾"),
            ("Nov-Dec", "Post harvest & storage", "📦"),
        ],
        "tomato": [
            ("Jan-Feb", "Nursery preparation", "🌱"),
            ("Mar-Apr", "Transplanting & staking", "🌿"),
            ("May-Jun", "Flowering & fruit set", "🌸"),
            ("Jul-Aug", "Disease monitoring", "🔍"),
            ("Sep-Oct", "Harvesting", "🍅"),
            ("Nov-Dec", "Land preparation", "🚜"),
        ],
        "wheat": [
            ("Oct-Nov", "Land preparation & sowing", "🌱"),
            ("Dec-Jan", "Irrigation & fertilizer", "💧"),
            ("Feb-Mar", "Pest & disease control", "🔍"),
            ("Apr", "Harvesting", "🌾"),
            ("May-Jun", "Storage & marketing", "📦"),
            ("Jul-Sep", "Off season preparation", "🚜"),
        ],
        "cotton": [
            ("Apr-May", "Land preparation & sowing", "🌱"),
            ("Jun-Jul", "Thinning & weeding", "🌿"),
            ("Aug-Sep", "Pest monitoring (bollworm)", "🔍"),
            ("Oct-Nov", "First picking", "☁️"),
            ("Dec-Jan", "Final picking", "☁️"),
            ("Feb-Mar", "Land preparation", "🚜"),
        ],
    }
    return calendars.get(crop.lower(), None)

init_db()

st.set_page_config(page_title="CropDoctor", page_icon="🌱", layout="wide")

st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
    * { font-family: 'Inter', sans-serif; }
    .stApp { background-color: #f0f4f0; }

    section[data-testid="stSidebar"] { background-color: #1a3a1a; }
    section[data-testid="stSidebar"] * { color: #ffffff !important; }
    section[data-testid="stSidebar"] .stButton button {
        background-color: #4caf50 !important;
        color: white !important;
        border-radius: 8px !important;
        width: 100% !important;
        font-weight: 600 !important;
    }

    .main-header {
        background: linear-gradient(135deg, #1a3a1a, #2d5a2d);
        padding: 32px;
        border-radius: 16px;
        margin-bottom: 28px;
        color: white;
    }
    .header-title { font-size: 2rem; font-weight: 700; letter-spacing: -0.03em; }
    .header-sub { font-size: 0.9rem; opacity: 0.75; margin-top: 6px; }

    h4 { color: #1a3a1a !important; font-weight: 700 !important; }

    .stTabs [data-baseweb="tab"] {
        font-size: 0.9rem !important;
        font-weight: 600 !important;
        color: #2d5a2d !important;
        background: white !important;
        border-radius: 8px 8px 0 0 !important;
        padding: 10px 20px !important;
    }
    .stTabs [aria-selected="true"] {
        background: #2d5a2d !important;
        color: white !important;
    }
    .stTabs [data-baseweb="tab-list"] {
        background: #e8f0e8 !important;
        border-radius: 10px !important;
        padding: 4px !important;
        gap: 4px !important;
    }

    .stat-card {
        background: white;
        border-radius: 12px;
        padding: 20px;
        text-align: center;
        border: 1px solid #e0e8e0;
        animation: fadeIn 0.4s ease;
    }
    .stat-icon { font-size: 1.8rem; margin-bottom: 6px; }
    .stat-value { font-size: 1.4rem; font-weight: 700; color: #1a1a1a; }
    .stat-label { font-size: 0.7rem; font-weight: 500; text-transform: uppercase; letter-spacing: 0.1em; color: #888; margin-top: 4px; }

    .result-card {
        background: white;
        border-radius: 16px;
        padding: 28px;
        border: 1px solid #e0e8e0;
        margin-bottom: 16px;
        animation: fadeIn 0.5s ease;
    }
    .severity-high { border-left: 5px solid #e53935; }
    .severity-medium { border-left: 5px solid #fb8c00; }
    .severity-low { border-left: 5px solid #43a047; }

    .info-row { margin-bottom: 20px; }
    .info-label { font-size: 0.7rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.1em; color: #888; margin-bottom: 4px; }
    .info-value { font-size: 0.95rem; color: #1a1a1a; line-height: 1.6; }

    .badge {
        display: inline-block;
        padding: 4px 14px;
        border-radius: 20px;
        font-weight: 700;
        font-size: 0.8rem;
    }
    .badge-high { background: #ffebee; color: #e53935; }
    .badge-medium { background: #fff3e0; color: #fb8c00; }
    .badge-low { background: #e8f5e9; color: #43a047; }

    .yield-bar-container {
        background: #f0f0f0;
        border-radius: 10px;
        height: 10px;
        margin-top: 6px;
        overflow: hidden;
    }
    .yield-bar-fill { height: 100%; border-radius: 10px; }

    .calendar-card {
        background: white;
        border-radius: 12px;
        padding: 16px 20px;
        border: 1px solid #e0e8e0;
        margin-bottom: 10px;
        display: flex;
        align-items: center;
        gap: 16px;
        animation: fadeIn 0.4s ease;
    }
    .cal-icon { font-size: 1.5rem; }
    .cal-month { font-size: 0.75rem; font-weight: 600; color: #2d5a2d; text-transform: uppercase; letter-spacing: 0.05em; }
    .cal-task { font-size: 0.9rem; color: #333; font-weight: 500; }

    @keyframes fadeIn {
        from { opacity: 0; transform: translateY(10px); }
        to { opacity: 1; transform: translateY(0); }
    }

    .stButton button {
        background-color: #2d5a2d !important;
        color: white !important;
        border-radius: 8px !important;
        font-weight: 600 !important;
    }
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="main-header">
    <div class="header-title">🌱 CropDoctor</div>
    <div class="header-sub">AI-powered crop disease diagnosis • Upload a photo • Get instant treatment in your language</div>
</div>
""", unsafe_allow_html=True)

with st.sidebar:
    st.markdown("### ⚙️ Settings")
    groq_key = st.text_input("Groq API Key", type="password", placeholder="gsk_...")
    language = st.selectbox("🌐 Language", ["English", "Telugu", "Hindi"])
    crop_name = st.text_input("🌾 Crop Name", placeholder="e.g. Rice, Tomato, Wheat")
    st.markdown("---")
    st.markdown("### 🌦️ Weather Risk")
    location = st.text_input("📍 Your Location", placeholder="e.g. Visakhapatnam")
    if location:
        weather = get_weather_risk(location)
        if weather:
            st.markdown(f"**{weather['desc']}** | 🌡️ {weather['temp']}°C | 💧 {weather['humidity']}%")
            st.markdown("**Disease Risks:**")
            for risk in weather['risks']:
                st.markdown(f"- {risk}")
        else:
            st.warning("Could not fetch weather. Check location name.")
    st.markdown("---")
    st.markdown("### 📋 How to use")
    st.markdown("""
    1. Enter your Groq API key
    2. Enter your crop name
    3. Select your language
    4. Enter your location
    5. Upload a photo
    6. Click **Diagnose**
    """)
    st.markdown("---")
    st.markdown("### 🌾 Supported Crops")
    st.markdown("Rice • Wheat • Tomato • Cotton • Maize • Potato • Sugarcane • Chilli")

tab1, tab2, tab3, tab4 = st.tabs(["🔍 Diagnose", "📅 Crop Calendar", "📱 SMS Report", "📁 History"])

with tab1:
    col1, col2 = st.columns([1, 1], gap="large")

    with col1:
        st.markdown("#### 📸 Upload Crop Photo")
        uploaded_file = st.file_uploader("Choose a photo of your crop", type=["jpg", "jpeg", "png"])
        if uploaded_file:
            st.image(uploaded_file, caption="Your crop photo", use_container_width=True)
        diagnose_btn = st.button("🔍 Diagnose Now", use_container_width=True)

        if diagnose_btn:
            if not groq_key:
                st.error("⚠️ Please enter your Groq API key in the sidebar.")
            elif not uploaded_file:
                st.error("⚠️ Please upload a crop photo first.")
            else:
                with st.spinner("🔬 Analysing your crop... Please wait"):
                    try:
                        image_data = encode_image(uploaded_file)
                        client = groq.Groq(api_key=groq_key)
                        lang_instruction = {
                            "Telugu": "Provide ALL text in Telugu language only.",
                            "Hindi": "Provide ALL text in Hindi language only.",
                            "English": "Provide all text in English."
                        }[language]

                        response = client.chat.completions.create(
                            model="meta-llama/llama-4-scout-17b-16e-instruct",
                            messages=[{
                                "role": "user",
                                "content": [
                                    {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_data}"}},
                                    {"type": "text", "text": f"""You are CropDoctor, an expert agricultural AI helping Indian farmers.

Analyze this crop image and respond ONLY with a valid JSON object. No extra text before or after.

{{
  "disease": "name of disease",
  "severity": "High or Medium or Low",
  "yield_loss": "e.g. 30-50%",
  "cause": "2-3 simple sentences about the cause",
  "treatment": "step by step treatment as plain text",
  "medicine": "specific pesticide or fungicide to buy",
  "prevention": "2-3 prevention tips as plain text"
}}

Crop: {crop_name if crop_name else 'Unknown'}
{lang_instruction}
Use simple language farmers can understand."""}
                                ]
                            }],
                            max_tokens=1024
                        )

                        raw = response.choices[0].message.content.strip()
                        if "```" in raw:
                            parts = raw.split("```")
                            for part in parts:
                                if "{" in part:
                                    raw = part
                                    break
                        if raw.startswith("json"):
                            raw = raw[4:].strip()
                        match = re.search(r'\{.*\}', raw, re.DOTALL)
                        if match:
                            raw = match.group()

                        data = json.loads(raw)
                        data['crop'] = crop_name or "Unknown"
                        data['language'] = language
                        data['date'] = datetime.now().strftime("%Y-%m-%d %H:%M")
                        st.session_state["diagnosis"] = data
                        save_diagnosis(
                            data['crop'], data['disease'], data['severity'],
                            data['yield_loss'], data['treatment'], data['medicine'], language
                        )
                        st.success("✅ Diagnosis complete!")

                    except json.JSONDecodeError:
                        st.session_state["diagnosis"] = {
                            "disease": "Analysis Complete", "severity": "Medium",
                            "yield_loss": "Unknown", "cause": "", "treatment": raw,
                            "medicine": "Consult local agri store",
                            "prevention": "Regular monitoring recommended",
                            "crop": crop_name or "Unknown", "language": language,
                            "date": datetime.now().strftime("%Y-%m-%d %H:%M")
                        }
                        st.success("✅ Diagnosis complete!")
                    except Exception as e:
                        st.error(f"Error: {str(e)}")

    with col2:
        st.markdown("#### 📊 Diagnosis Result")
        if "diagnosis" in st.session_state:
            d = st.session_state["diagnosis"]
            sev = d.get("severity", "Medium").lower()
            sev_class = f"severity-{sev}"
            badge_class = f"badge-{sev}"
            yield_str = d.get("yield_loss", "0%")
            try:
                yield_num = int(''.join(filter(str.isdigit, yield_str.split('-')[0])))
            except:
                yield_num = 30
            yield_color = "#e53935" if yield_num > 50 else "#fb8c00" if yield_num > 20 else "#43a047"

            s1, s2, s3 = st.columns(3)
            with s1:
                st.markdown(f"""<div class="stat-card">
                    <div class="stat-icon">🦠</div>
                    <div class="stat-value" style="font-size:0.85rem">{d.get('disease','')[:25]}</div>
                    <div class="stat-label">Disease</div>
                </div>""", unsafe_allow_html=True)
            with s2:
                st.markdown(f"""<div class="stat-card">
                    <div class="stat-icon">⚠️</div>
                    <div class="stat-value"><span class="badge {badge_class}">{d.get('severity','')}</span></div>
                    <div class="stat-label">Severity</div>
                </div>""", unsafe_allow_html=True)
            with s3:
                st.markdown(f"""<div class="stat-card">
                    <div class="stat-icon">📉</div>
                    <div class="stat-value">{d.get('yield_loss','')}</div>
                    <div class="stat-label">Yield Loss</div>
                </div>""", unsafe_allow_html=True)

            st.markdown("<br>", unsafe_allow_html=True)
            st.markdown(f"""
            <div class="result-card {sev_class}">
                <div class="info-row">
                    <div class="info-label">📉 Estimated Yield Loss</div>
                    <div class="yield-bar-container">
                        <div class="yield-bar-fill" style="width:{yield_num}%; background:{yield_color};"></div>
                    </div>
                    <div style="font-size:0.8rem; color:#888; margin-top:4px;">{yield_str} if untreated</div>
                </div>
                <div class="info-row">
                    <div class="info-label">🔍 Cause</div>
                    <div class="info-value">{d.get('cause','')}</div>
                </div>
                <div class="info-row">
                    <div class="info-label">💊 Treatment</div>
                    <div class="info-value">{d.get('treatment','').replace(chr(10), '<br>')}</div>
                </div>
                <div class="info-row">
                    <div class="info-label">🛒 Medicine to Buy</div>
                    <div class="info-value">{d.get('medicine','')}</div>
                </div>
                <div class="info-row">
                    <div class="info-label">🛡️ Prevention</div>
                    <div class="info-value">{d.get('prevention','').replace(chr(10), '<br>')}</div>
                </div>
            </div>
            """, unsafe_allow_html=True)

            report = generate_report(d)
            st.download_button(
                label="📄 Download Report",
                data=report,
                file_name=f"CropDoctor_{d['crop']}_{d['date'].replace(':', '-')}.txt",
                mime="text/plain",
                use_container_width=True
            )
        else:
            st.markdown("""
            <div class="result-card">
                <div style="text-align:center; padding: 60px 0; color: #aaa;">
                    <div style="font-size: 3rem;">🌿</div>
                    <div style="margin-top: 12px; font-weight: 500; color: #555;">No diagnosis yet</div>
                    <div style="font-size: 0.85rem; margin-top: 6px;">Upload a photo and click Diagnose Now</div>
                </div>
            </div>
            """, unsafe_allow_html=True)

with tab2:
    st.markdown("#### 📅 Crop Calendar")
    st.markdown("Select your crop to see the full farming calendar with tasks for each month.")
    selected_crop = st.selectbox("🌾 Select Crop", ["Rice", "Tomato", "Wheat", "Cotton"])
    calendar = get_crop_calendar(selected_crop)
    if calendar:
        current_month = datetime.now().month
        month_map = {1:"Jan",2:"Feb",3:"Mar",4:"Apr",5:"May",6:"Jun",7:"Jul",8:"Aug",9:"Sep",10:"Oct",11:"Nov",12:"Dec"}
        current_month_str = month_map[current_month]
        for month, task, icon in calendar:
            is_current = current_month_str in month
            highlight = "border: 2px solid #4caf50; background: #f1f8f1;" if is_current else ""
            current_tag = " 👈 <span style='color:#4caf50;font-size:0.75rem;font-weight:600'>NOW</span>" if is_current else ""
            st.markdown(f"""
            <div class="calendar-card" style="{highlight}">
                <div class="cal-icon">{icon}</div>
                <div>
                    <div class="cal-month">{month}{current_tag}</div>
                    <div class="cal-task">{task}</div>
                </div>
            </div>
            """, unsafe_allow_html=True)
    else:
        st.info("Calendar not available for this crop yet.")

with tab3:
    st.markdown("#### 📱 SMS Report")
    st.markdown("Send the diagnosis report directly to your phone or the farmer's phone.")
    phone = st.text_input("📱 Phone Number", placeholder="+91 9999999999")
    sms_col1, sms_col2 = st.columns(2)
    with sms_col1:
        twilio_sid = st.text_input("Twilio Account SID", type="password", placeholder="ACxxxxxxxx")
    with sms_col2:
        twilio_token = st.text_input("Twilio Auth Token", type="password", placeholder="xxxxxxxx")
    twilio_from = st.text_input("Twilio Phone Number", placeholder="+1xxxxxxxxxx")

    if st.button("📤 Send SMS Report", use_container_width=True):
        if "diagnosis" not in st.session_state:
            st.error("⚠️ No diagnosis yet. Please diagnose a crop first.")
        elif not phone:
            st.error("⚠️ Please enter a phone number.")
        elif not twilio_sid or not twilio_token or not twilio_from:
            st.error("⚠️ Please enter your Twilio credentials.")
        else:
            try:
                from twilio.rest import Client
                d = st.session_state["diagnosis"]
                message = f"""🌱 CropDoctor Report
Crop: {d['crop']}
Disease: {d['disease']}
Severity: {d['severity']}
Yield Loss: {d['yield_loss']}

Treatment: {d['treatment'][:200]}...

Medicine: {d['medicine']}

Generated by CropDoctor AI"""
                client = Client(twilio_sid, twilio_token)
                client.messages.create(body=message, from_=twilio_from, to=phone)
                st.success(f"✅ SMS sent to {phone}!")
            except Exception as e:
                st.error(f"SMS Error: {str(e)}")

with tab4:
    st.markdown("#### 📁 Diagnosis History")
    diagnoses = get_all_diagnoses()
    if diagnoses:
        import pandas as pd
        df = pd.DataFrame(diagnoses, columns=["ID", "Crop", "Disease", "Severity", "Yield Loss", "Treatment", "Medicine", "Language", "Date"])
        st.dataframe(df.drop(columns=["ID", "Treatment"]), use_container_width=True, hide_index=True)
    else:
        st.info("No diagnoses yet. Upload a crop photo to get started!")